version: "3"

services:
  flask_web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      - DB_HOST=10.10.8.103
      - DB_PORT=5432
      - DB_NAME=musicdb
      - DB_USER=musicuser
      - DB_PASSWORD=musicpass


