apiVersion: v1
kind: Pod
metadata:
  name: web-nginx
  namespace: ns2
spec:
  containers:
    - image: nginx:1.14
      name: nginx
      ports:
        - containerPort: 80
        - containerPort: 443
